### PR TITLE
Fix the lack of tab/focus for password indicators, and add aria-live to it and maxLength.

### LINKED ISSUE #250: Password visibilty button is not tabbable
When you're tabbing through inputs you should be able to select the password visibility button and select it.

Additionally this should probably apply to the maxLength counter in some sort of way.

### PR DESCRIPTION
**Pull request by MelissaAutumn**
Fixes #250 

Will need some german l10n from @devmount here.  :sweat_smile: 

This makes password indicator tabbable which fixes the a11y issue. For a better time I added aria-polite and adjusted the v-ifs to avoid losing element focus when the indicator changes. 

I also added a custom aria label for maxLength which works quite well.

### CODE REVIEW

File: src/components/TextInput.vue [hunk 1]
```diff
@@ -140,13 +149,19 @@ const charCount = computed(() => model.value?.length ?? 0);
...
+          class="tbpro-input-suffix" 
+          aria-live="polite" 
+          tabindex="0" 
+          :title="passwordIndicatorText"
+          @keyup.space="togglePasswordVisibility" 
+          @click="togglePasswordVisibility"
+          v-if="passwordIsVisible !== null" 
+        >
+          <eye-icon class="icon" alt="" v-if="passwordIsVisible === true" />
+          <eye-off-icon class="icon" alt="" v-else-if="passwordIsVisible === false" />
```
Comment (davinotdavid) [inline src/components/TextInput.vue:162]: We could shorten this to

```suggestion
          <eye-icon class="icon" alt="" v-if="passwordIsVisible" />
          <eye-off-icon class="icon" alt="" v-else />
```

File: src/components/TextInput.vue [hunk 2]
```diff
@@ -140,13 +149,19 @@ const charCount = computed(() => model.value?.length ?? 0);
...
-        <span v-else-if="passwordIsVisible === false" class="tbpro-input-suffix" @click="togglePasswordVisibility">
-          <eye-off-icon class="icon" />
+        <span 
+          class="tbpro-input-suffix" 
+          aria-live="polite" 
+          tabindex="0" 
+          :title="passwordIndicatorText"
+          @keyup.space="togglePasswordVisibility" 
+          @click="togglePasswordVisibility"
+          v-if="passwordIsVisible !== null"
```
Comment (davinotdavid) [inline src/components/TextInput.vue:159]: Similarly, I believe this would be enough instead


```suggestion
          v-if="isPasswordField"
```

File: src/components/TextInput.vue
Comment (davinotdavid) [inline src/components/TextInput.vue:108]: Shouldn't this be 

```suggestion
const passwordIsVisible = ref(!isPasswordField);
```

instead?

File: src/components/TextInput.vue [hunk 3]
```diff
@@ -106,6 +110,11 @@ const passwordIsVisible = ref(isPasswordField ? false : null);
 const togglePasswordVisibility = () => {
   inputType.value = passwordIsVisible.value ? 'password' : 'text';
   passwordIsVisible.value = !passwordIsVisible.value;
+  if (passwordIsVisible.value === true) {
+    passwordIndicatorText.value = hidePasswordText;
+  } else if (passwordIsVisible.value === false) {
+    passwordIndicatorText.value = showPasswordText;
+  }
```
Comment (davinotdavid) [inline src/components/TextInput.vue:117]: If we eliminate the `true` / `false` / `null` to use `isPasswordField` and `passwordIsVisible` we could do:


```suggestion
  passwordIndicatorText.value = passwordIsVisible.value ? hidePasswordText : showPasswordText
```

**Review by davinotdavid — CHANGES_REQUESTED** [review]
Nice! The a11y related changed looks good to me but some questions on the boolean handling

**Comment by MelissaAutumn** [comment]
We should punt that to a different ticket as the current method of using true, false and null as separate values is a separate issue and requires additional testing here.

**Comment by MelissaAutumn** [comment]
Created https://github.com/thunderbird/services-ui/issues/257

**Review by davinotdavid — APPROVED** [review]

**Review by devmount — APPROVED** [review]
Nice, thanks for this! I added the missing German bits from this PR and sneaked in one that was missing for a longer time apparently 😇

**Comment by devmount** [comment]
Also: This PR has a nice round PR number of 256 😍
