### PR TITLE
Fix TextInput being marked dirty from focus

### LINKED ISSUE #99: TextInput should be able to receive / forward the `readonly` attribute
Currently, the `TextInput` is able to receive `disabled` but not `readonly`. It would be very nice to have it for situations like the one below, where we still want to keep the "clicking the label auto-selects the text" property (which doesn't work if the input is disabled).

Image

https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Attributes/readonly

### LINKED ISSUE #254: TextInput should not immediately mark input as dirty
This is a bit of an annoying bug, if you touch an empty text input it'll be marked as dirty. 

The actual behaviour is if you write anything (even if you remove the contents after) it should be marked as dirty.

### PR DESCRIPTION
**Pull request by MelissaAutumn**
Fixes #254 
Fixes #99 

We should only be marking a text input as dirty if we change something in it, and not when we simply focus and blur away. This fixes my main annoyance with our textinput :smile: 

Also I added a story for #99 and confirmed readonly works as intended.

### CODE REVIEW

**Review by devmount — APPROVED** [review]
Nice, thanks so much for this fix! I can take a look at the other input components for #207

File: src/components/TextInput.vue [hunk 1]
```diff
@@ -80,16 +79,15 @@ const onInvalid = (evt: HTMLInputElementEvent) => {
...
-  isInvalid.value = false;
   isDirty.value = true;
+  isInvalid.value = false;
   validationMessage.value = '';
+  inputRef.value.setCustomValidity('');
 };
 
 const onBlur = (evt) => {
-  if (evt.target.checkValidity()) {
+  if (isDirty.value && evt.target.checkValidity()) {
```
Comment (davinotdavid) [inline src/components/TextInput.vue:89]: If the text input is marked as required, should the blur on an empty text input trigger the `checkValidity`? That would mean that the user "passed through" without filling the input itself.

Ref https://thunderbird.github.io/services-ui/?path=/story/components-textinput--required

Comment (MelissaAutumn) [reply src/components/TextInput.vue:89]: Thankfully that is covered automatically for us!
https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Attributes/required#constraint_validation

We already show "this field is required" we don't need to warn them about how the field is empty until we check for validation OR unless they dirty the input.

**Comment by MelissaAutumn** [comment]
> Nice, thanks so much for this fix! I can take a look at the other input components for #207

Oh that's where the ticket was. I thought we had one but couldn't find it and this issue was driving me crazy. Please do though :smile:

**Review by davinotdavid — APPROVED** [review]

File: src/components/TextInput.vue (hunk 1 above)
Comment (davinotdavid) [reply src/components/TextInput.vue:89]: Ah I thought that we wanted to warn them with our own error design instead of mixing in the built-in styles. All good then!
